@startuml
'https://plantuml.com/sequence-diagram
title use-case 2: Continue Game


Game -> Game: loadPlayerData()
Game -> IO: data[]=readPlayerData()
alt data[] not empty
loop
Game -> Game: createPlayer(name, balance);
Game -> Player: new(name, balance)
end

else
Game -> Game: registerPlayers()
note left
see use-case startNewGame
end note
end
Game -> Game: displayPlayers()
Game -> Game: runGameLoop();



@enduml

