@startuml
'https://plantuml.com/sequence-diagram

participant Game as game
participant TextUI as ui
participant Property as subField
participant Field  as field


game -> game : landAndAct(f)
game -> subField : msg = onLand(player)
subField -> field : msg = super.onLand(player);
field --> subField: "Egon er landet på Valbylanggade"

alt owner == null
 subField -> subField : this.option = "buy" \nmsg +=  "Vil du købe Valbylanggade? Y/N"
else if owner != player
 subField -> subField :  this.option = "pay"\nmsg += "Betal 2000kr i husleje. Indforstået? Y/N"
 subField -> Player :payRent(this.income, this.owner)
end

subField --> game : "Egon er landet på Valbylanggade. Vil du købe Valbylanggade? Y/N"
@enduml