@startuml
'https://plantuml.com/sequence-diagram

Main -> Game: new()
Game -> UI: new()
Game -> IO: new()
Main -> Game: runDialog()
Game -> UI: displayMsg("Welcome")
loop
Game -> UI: action= promptChoice("Choose action", listOfActions)
alt action 1: Start new game

end
alt action 2: Continue game

end
Game -> IO:saveGame()
end

@enduml