@startuml
'https://plantuml.com/sequence-diagram

participant Game as game
participant TextUI as ui
participant Property  as subField
participant Field  as field

game -> ui : response = promptText( msg )

ui --> game : "Y"
game -> field : msg = processResponse(player, response )

alt response "Y"
    field  -> subField : onAccept(player)

    alt option == "buy"
        subField  -> Player: buyProperty(this)
        Player -> Account : withdraw(costOfField)
    subField --> game : "Egon købte Valbylanggade"

    else if option == "pay"
             subField -> Player :payRent(rent, owner)
             Player -> Account : withdraw(rent)
             Player -> Account : owner.deposit(rent)
             subField --> game : "Egon betalte for at stå på Valbylanggade"
    end

else response "N"
    field -> subField : onReject(player)
    end


game -> ui : displayMessage( msg )

@enduml