@startuml
'https://plantuml.com/sequence-diagram

participant Game as game
participant TextUI as ui
participant Property as subField
participant Field  as field


game -> game : landAndAct(f)
game -> subField : msg = onLand(player)
subField -> field : msg = super.onLand(player);
field --> subField: "Egon er landet på Valbylanggade"

alt owner == null
 subField -> subField : this.option = "buy" \nmsg +=  "Vil du købe Valbylanggade? Y/N"
else if owner != player
 subField -> subField :  this.option = "pay"\nmsg += "Betal 2000kr i husleje. Indforstået? Y/N"
 subField -> Player :payRent(this.income, this.owner)
end

subField --> game : "Egon er landet på Valbylanggade. Vil du købe Valbylanggade? Y/N"

game -> ui : response = promptText( msg )

ui --> game : "Y"
game -> field : msg = processResponse(player, response )

alt response "Y"
    field  -> subField : onAccept(player)

    alt option == "buy"
        subField  -> Player: buyProperty(this)
        Player -> Account : withdraw(costOfField)
    subField --> game : "Egon købte Valbylanggade"

    else if option == "pay"
             subField -> Player :payRent(rent, owner)
             Player -> Account : withdraw(rent)
             Player -> Account : owner.deposit(rent)
    end

else response "N"
    field -> subField : onReject(player)
    end

game -> ui : displayMessage( msg )


' only in Plot.onLand
' alt this.isMonopolised
' subField -> subField :  this.option = "build"\nmsg = "Vil du bygge? Y/N"'

@enduml
