@startuml
!pragma layout smetana

  actor user

  usecase "ThrowAndMove" as UC3
  usecase "StartGame" as UC1
  usecase "EndGame" as UC5
  usecase "RegisterPlayers" as UC2
  usecase "LandAndAct" as UC4
  usecase "pawnOrTrade" as UC6

user --> UC1
UC1 --> UC2
UC1 --> UC3
UC3 --> UC6
UC3 --> UC4
UC4 --> UC3
UC3 --> UC5
UC1 --> UC5
@enduml
